
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}
          restore-keys: bundle-${{ matrix.ruby }}
      - run: bundle install --jobs 4 --retry 3 --path vendor/bundle
      - run: bundle exec rake
